const port = process.env.PORT || 5000

const option = {
  definition: {
    openapi: '3.1.0',
    info: {
      title: 'Pengembangan Aplikasi Web Backend',
      version: '0.0.0',
      description:
        'This project is part of our final task from Web Development course that contains a backend API for managing food recipes using Express.js and MongoDB. You can do CRUD operation for recipe, inventory, order, delivery, and auth feature.',
    },
    components: {
      schemas: {
        Order: {
          type: 'object',
          properties: {
            _id: {
              type: 'string',
              description: 'The unique identifier for the order. Automatically generated by mongo.',
            },
            date: {
              type: 'string',
              format: 'date',
              description: 'The date of the order.',
            },
            items: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  product: {
                    type: 'string',
                    description: 'The name of the product.',
                  },
                  quantity: {
                    type: 'number',
                    description: 'The quantity of the product.',
                  },
                  price: {
                    type: 'number',
                    description: 'The price of the product.',
                  },
                },
              },
              description: 'The list of items in the order.',
            },
            totalPrice: {
              type: 'number',
              description: 'The total price of the order.',
            },
            karyawan: {
              type: 'string',
              description: 'The ID of the associated Karyawan (employee).',
            },
          },
        },
      },
    },
    servers: [
      {
        url: `http://127.0.0.1:${port}`,
      },
    ],
  },
  apis: ['./routes/*.js'],
}

module.exports = option
